### ISSUE TITLE
key table backup, feat. local storage resetting with some regularity

### ISSUE THREAD

**Issue by pleonasticTautology** [a2aaron/Cohoard#51]
i'm not sure if this is an issue you are a8le to address, 8ut every so often, it seems cohoard loses/deletes the local storage, meaning we have to reload all of the stuff into the ta8le.

1) is there a known way to prevent this?
2) do you think it would 8e possi8le to add "import from csv"/"export to csv" options so we can 8ack things up/type them up manually and upload?

**Comment by a2aaron** [comment]
1. Hm, I've never experienced this bug--are you able to reliably trigger it? It'd help with debugging this. I don't know what would cause this other than the browser/OS clearing localStorage for some reason. If it does happen again, can you check the Console in the Developer Tools? If the localStorage data doesn't load for any reason, it should log an error there and I can use that help debug it.

2. Sure! I will export it as JSON instead of CSV, if that's okay, though.

**Comment by a2aaron** [comment]
Okay! I've implemented the import/export feature. Hopefully, the JSON it outputs is reasonably human editable. I'll keep this issue open for a little bit for feedback, and then close it eventually if you find the feature to be good. If you find a way to reproduce the localStorage bug, please let me know, since I can't seem to reproduce it.

Thank you for your request!

**Comment by a2aaron** [comment]
Ah, a friend has noted that [localStorage can get cleared for a few different reasons](https://stackoverflow.com/a/37105645), depending on browser. In particular, it looks like "Local storage can get cleared when updating chrome". If you're on Chrome, maybe that is the reason? (I don't think Cohoard is storing too much in localStorage--it's significantly less than 1 MB even when saving lots of templates or table entries, which should almost certainly mean it doesn't get pruned for size, I think?)

**Comment by pleonasticTautology** [comment]
we use safari

also it cleared again since this but that may be due to the update — Dave

**Comment by pleonasticTautology** [comment]
as for the exporter: works perfectly, "human"-readable, editable in vs code, so all good there — Dave

**Comment by a2aaron** [comment]
(Sorry for late response!)

Ah, if you're on safari, then [WebKit deletes localStorage every 7 days for third party scripts](https://webkit.org/blog/10218/full-third-party-cookie-blocking-and-more/). ~~I might be able to put all of the JS/WASM bundle onto Github Pages (currently I'm serving it from a friend's server). Maybe that will fix the clearing? I'll see if I can do that.~~

**EDIT**: Seems like there's no way for a website to mark its own localStorage as "please don't delete this"? Even if I served all scripts from the github page itself, seems like WebKit will clear the data regardless. Sorry about this, I don't think I can fix this on my end.

In the meantime, maybe adding Cohoard to the homescreen might help? I'm not sure if that an iOS safari only thing though. This paragraph from the linked page suggests that might prevent localStorage deletion.

> A Note On Web Applications Added to the Home Screen
> As mentioned, the seven-day cap on script-writable storage is gated on “after seven days of Safari use without user interaction on the site.” That is the case in Safari. Web applications added to the home screen are not part of Safari and thus have their own counter of days of use. Their days of use will match actual use of the web application which resets the timer. We do not expect the first-party in such a web application to have its website data deleted.

**Comment by pleonasticTautology** [comment]
oh we're doing 99% of cohoard stuff on desktop, so having the json honestly works out for the best. thanks for checking into this, though! — alphy
